import Providers from "@/providers/query-client-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-slate-950 ${inter.className}`}>
        <nav className="py-10 mb-10">
          <div className="container mx-auto max-w-5xl flex justify-between">
            <h1 className="text-white text-xl font-bold">Quiktest</h1>
            <div className="flex text-white gap-10 text-sm">
              <Link href="/reports">Test reports</Link>
              <Link href="/testcases">Testcases</Link>
            </div>
          </div>
        </nav>
        <div className="container mx-auto max-w-4xl">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
